use serde_json::{Map, Value, json};

use super::tool_registry::ToolRegistry;
use super::types::{ToolResult, ToolStatus};
use crate::runtime::context::RuntimeContext;
use crate::runtime::errors::GlyphRuntimeError;

pub fn create_mock_tool_registry() -> ToolRegistry {
    let mut registry = ToolRegistry::new();
    registry
        .register("SPEC", spec_tool)
        .register("PLAN", plan_tool)
        .register("GEN", gen_tool)
        .register("CHECK", check_tool)
        .register("FIX", fix_tool)
        .register("PATCH", patch_tool)
        .register("SUM", summarize_tool)
        .register("SUMMARIZE", summarize_tool)
        .register("ASK", ask_tool)
        .register("EXPORT", export_tool)
        .register("RUN", run_tool)
        .register("READ", read_tool)
        .register("WRITE", write_tool);
    registry
}

fn spec_tool(
    args: Map<String, Value>,
    _ctx: &mut RuntimeContext,
) -> Result<ToolResult, GlyphRuntimeError> {
    Ok(ToolResult {
        status: ToolStatus::Pass,
        value: json!({
            "kind": "spec",
            "normalized": true,
            "requirements": args
        }),
        summary: format!(
            "Specification captured ({} field{})",
            args.len(),
            if args.len() == 1 { "" } else { "s" }
        ),
        warnings: vec![],
    })
}

fn plan_tool(
    args: Map<String, Value>,
    _ctx: &mut RuntimeContext,
) -> Result<ToolResult, GlyphRuntimeError> {
    let input = args
        .get("input")
        .or_else(|| args.get("spec"))
        .cloned()
        .unwrap_or_else(|| Value::Object(args.clone()));
    Ok(ToolResult {
        status: ToolStatus::Pass,
        value: json!({
            "kind": "plan",
            "input": input,
            "steps": ["spec", "generate", "check", "repair", "export"]
        }),
        summary: "Structured plan created".to_string(),
        warnings: vec![],
    })
}

fn gen_tool(
    args: Map<String, Value>,
    _ctx: &mut RuntimeContext,
) -> Result<ToolResult, GlyphRuntimeError> {
    Ok(ToolResult {
        status: ToolStatus::Warning,
        value: json!({
            "kind": "file_bundle",
            "files": [{
                "path": "src/index.ts",
                "content": "// generated by Glyph mock GEN\nexport const generated = true;\n"
            }],
            "metadata": args,
            "issues": ["mock_quality_review"],
            "patches": 0
        }),
        summary: "Mock file bundle generated".to_string(),
        warnings: vec!["Generated bundle requires a mock quality pass".to_string()],
    })
}

fn check_tool(
    args: Map<String, Value>,
    _ctx: &mut RuntimeContext,
) -> Result<ToolResult, GlyphRuntimeError> {
    let target = args
        .get("target")
        .or_else(|| args.get("input"))
        .cloned()
        .unwrap_or_else(|| Value::Object(args.clone()));
    let using = args
        .get("using")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let issues = extract_issues(&target);
    let status = if issues.is_empty() {
        if using.iter().any(|item| item == "risk") {
            ToolStatus::Warning
        } else {
            ToolStatus::Pass
        }
    } else {
        ToolStatus::Fail
    };
    let using_strings = using
        .iter()
        .filter_map(Value::as_str)
        .map(ToString::to_string)
        .collect::<Vec<_>>();

    Ok(ToolResult {
        status,
        value: json!({
            "kind": "check_report",
            "status": status.as_str(),
            "using": using,
            "issues": issues,
            "targetSummary": summarize_value(&target)
        }),
        summary: format!(
            "Check {}{}",
            status.as_str(),
            if using_strings.is_empty() {
                String::new()
            } else {
                format!(" via {}", using_strings.join(", "))
            }
        ),
        warnings: if status == ToolStatus::Fail {
            extract_issues(&target)
        } else {
            vec![]
        },
    })
}

fn fix_tool(
    args: Map<String, Value>,
    _ctx: &mut RuntimeContext,
) -> Result<ToolResult, GlyphRuntimeError> {
    let target = args
        .get("target")
        .or_else(|| args.get("input"))
        .cloned()
        .unwrap_or(Value::Null);
    let value = patch_value(
        target,
        json!({
            "fixed": true,
            "issues": [],
            "lastReport": args.get("report").cloned().unwrap_or(Value::Null),
            "max": args.get("max").cloned().unwrap_or(Value::Null)
        }),
    );

    Ok(ToolResult {
        status: ToolStatus::Pass,
        value,
        summary: "Mock fix applied".to_string(),
        warnings: vec![],
    })
}

fn patch_tool(
    args: Map<String, Value>,
    _ctx: &mut RuntimeContext,
) -> Result<ToolResult, GlyphRuntimeError> {
    let target = args
        .get("target")
        .or_else(|| args.get("input"))
        .cloned()
        .unwrap_or(Value::Null);
    let value = patch_value(
        target,
        json!({
            "patched": true,
            "instructions": args.get("instructions").cloned().unwrap_or(Value::Null)
        }),
    );

    Ok(ToolResult {
        status: ToolStatus::Pass,
        value,
        summary: "Mock patch applied".to_string(),
        warnings: vec![],
    })
}

fn summarize_tool(
    args: Map<String, Value>,
    _ctx: &mut RuntimeContext,
) -> Result<ToolResult, GlyphRuntimeError> {
    let target = args
        .get("target")
        .or_else(|| args.get("input"))
        .cloned()
        .unwrap_or_else(|| Value::Object(args.clone()));
    Ok(ToolResult {
        status: ToolStatus::Pass,
        value: json!({
            "kind": "summary",
            "text": summarize_value(&target),
            "target": target
        }),
        summary: "Summary created".to_string(),
        warnings: vec![],
    })
}

fn ask_tool(
    args: Map<String, Value>,
    _ctx: &mut RuntimeContext,
) -> Result<ToolResult, GlyphRuntimeError> {
    let answer = args
        .get("options")
        .and_then(Value::as_array)
        .and_then(|options| options.first())
        .cloned()
        .unwrap_or_else(|| Value::String("mock answer".to_string()));

    Ok(ToolResult {
        status: ToolStatus::Pass,
        value: json!({
            "kind": "answer",
            "question": args.get("question").or_else(|| args.get("input")).cloned().unwrap_or(Value::Null),
            "answer": answer
        }),
        summary: "Mock answer selected".to_string(),
        warnings: vec![],
    })
}

fn export_tool(
    args: Map<String, Value>,
    _ctx: &mut RuntimeContext,
) -> Result<ToolResult, GlyphRuntimeError> {
    let format = args
        .get("format")
        .and_then(Value::as_str)
        .unwrap_or("json")
        .to_string();
    Ok(ToolResult {
        status: ToolStatus::Pass,
        value: json!({
            "kind": "artifact",
            "format": format,
            "uri": format!("mock://export/{format}"),
            "target": args.get("target").or_else(|| args.get("input")).cloned().unwrap_or_else(|| Value::Object(args.clone()))
        }),
        summary: format!("Artifact exported as {format}"),
        warnings: vec![],
    })
}

fn run_tool(
    args: Map<String, Value>,
    _ctx: &mut RuntimeContext,
) -> Result<ToolResult, GlyphRuntimeError> {
    Ok(ToolResult {
        status: ToolStatus::Pass,
        value: json!({
            "kind": "command_result",
            "command": args.get("command").or_else(|| args.get("input")).cloned().unwrap_or(Value::Null),
            "target": args.get("target").cloned().unwrap_or(Value::Null),
            "exitCode": 0,
            "stdout": "Mock RUN did not execute a real shell command."
        }),
        summary: "Mock command completed".to_string(),
        warnings: vec![],
    })
}

fn read_tool(
    args: Map<String, Value>,
    ctx: &mut RuntimeContext,
) -> Result<ToolResult, GlyphRuntimeError> {
    let path = args
        .get("path")
        .or_else(|| args.get("input"))
        .and_then(Value::as_str)
        .unwrap_or("")
        .to_string();
    let value = ctx.read_file(&path).cloned().unwrap_or_else(|| {
        if path == "app" {
            json!({
                "kind": "file_bundle",
                "path": path,
                "files": [{
                    "path": "app/index.ts",
                    "content": "export const broken = true;\n"
                }],
                "issues": ["failing_tests"],
                "patches": 0
            })
        } else {
            json!({
                "kind": "file",
                "path": path,
                "content": ""
            })
        }
    });

    Ok(ToolResult {
        status: ToolStatus::Pass,
        value,
        summary: format!("Read {}", if path.is_empty() { "mock path" } else { &path }),
        warnings: vec![],
    })
}

fn write_tool(
    args: Map<String, Value>,
    ctx: &mut RuntimeContext,
) -> Result<ToolResult, GlyphRuntimeError> {
    let path = args
        .get("path")
        .or_else(|| args.get("input"))
        .and_then(Value::as_str)
        .unwrap_or("")
        .to_string();
    let content = args
        .get("content")
        .cloned()
        .unwrap_or(Value::String(String::new()));
    ctx.write_file(path.clone(), content.clone());

    Ok(ToolResult {
        status: ToolStatus::Pass,
        value: json!({
            "kind": "write_result",
            "path": path,
            "content": content,
            "written": true
        }),
        summary: format!(
            "Wrote {}",
            if path.is_empty() { "mock path" } else { &path }
        ),
        warnings: vec![],
    })
}

fn extract_issues(value: &Value) -> Vec<String> {
    value
        .get("issues")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(Value::as_str)
                .map(ToString::to_string)
                .collect()
        })
        .unwrap_or_default()
}

fn patch_value(target: Value, patch: Value) -> Value {
    match (target, patch) {
        (Value::Object(mut target), Value::Object(patch)) => {
            let patches = target.get("patches").and_then(Value::as_i64).unwrap_or(0) + 1;
            for (key, value) in patch {
                target.insert(key, value);
            }
            target.insert("patches".to_string(), Value::from(patches));
            Value::Object(target)
        }
        (target, Value::Object(mut patch)) => {
            patch.insert(
                "kind".to_string(),
                Value::String("patched_value".to_string()),
            );
            patch.insert("target".to_string(), target);
            patch.insert("patches".to_string(), Value::from(1));
            Value::Object(patch)
        }
        (target, _) => json!({
            "kind": "patched_value",
            "target": target,
            "patches": 1
        }),
    }
}

fn summarize_value(value: &Value) -> String {
    match value {
        Value::Null => "null".to_string(),
        Value::String(value) => value.clone(),
        Value::Number(value) => value.to_string(),
        Value::Bool(value) => value.to_string(),
        Value::Array(items) => format!("array with {} items", items.len()),
        Value::Object(object) => object
            .get("kind")
            .and_then(Value::as_str)
            .map(|kind| format!("{kind} object"))
            .unwrap_or_else(|| format!("object with {} keys", object.len())),
    }
}
