import { ToolRegistry } from "./toolRegistry.js";
import type { ToolResult, ToolStatus } from "./types.js";

export function createMockToolRegistry(): ToolRegistry {
  return new ToolRegistry()
    .register("SPEC", specTool)
    .register("PLAN", planTool)
    .register("GEN", genTool)
    .register("CHECK", checkTool)
    .register("FIX", fixTool)
    .register("PATCH", patchTool)
    .register("SUM", summarizeTool)
    .register("SUMMARIZE", summarizeTool)
    .register("ASK", askTool)
    .register("EXPORT", exportTool)
    .register("RUN", runTool)
    .register("READ", readTool)
    .register("WRITE", writeTool);
}

function specTool(args: Record<string, unknown>): ToolResult {
  return {
    status: "pass",
    value: {
      kind: "spec",
      normalized: true,
      requirements: args
    },
    summary: `Specification captured (${Object.keys(args).length} field${Object.keys(args).length === 1 ? "" : "s"})`
  };
}

function planTool(args: Record<string, unknown>): ToolResult {
  const input = args.input ?? args.spec ?? args;
  return {
    status: "pass",
    value: {
      kind: "plan",
      input,
      steps: ["spec", "generate", "check", "repair", "export"]
    },
    summary: "Structured plan created"
  };
}

function genTool(args: Record<string, unknown>): ToolResult {
  return {
    status: "warning",
    value: {
      kind: "file_bundle",
      files: [
        {
          path: "src/index.ts",
          content: "// generated by Glyph mock GEN\nexport const generated = true;\n"
        }
      ],
      metadata: args,
      issues: ["mock_quality_review"],
      patches: 0
    },
    summary: "Mock file bundle generated",
    warnings: ["Generated bundle requires a mock quality pass"]
  };
}

function checkTool(args: Record<string, unknown>): ToolResult {
  const target = args.target ?? args.input ?? args;
  const using = Array.isArray(args.using) ? args.using : [];
  const issues = extractIssues(target);
  const status: ToolStatus = issues.length > 0 ? "fail" : using.includes("risk") ? "warning" : "pass";
  const report = {
    kind: "check_report",
    status,
    using,
    issues,
    targetSummary: summarizeValue(target)
  };

  return {
    status,
    value: report,
    summary: `Check ${status}${using.length ? ` via ${using.join(", ")}` : ""}`,
    warnings: status === "fail" ? issues : undefined
  };
}

function fixTool(args: Record<string, unknown>): ToolResult {
  const target = args.target ?? args.input;
  const report = args.report;
  const value = patchValue(target, {
    fixed: true,
    issues: [],
    lastReport: report,
    max: args.max
  });

  return {
    status: "pass",
    value,
    summary: "Mock fix applied"
  };
}

function patchTool(args: Record<string, unknown>): ToolResult {
  const value = patchValue(args.target ?? args.input, {
    patched: true,
    instructions: args.instructions
  });

  return {
    status: "pass",
    value,
    summary: "Mock patch applied"
  };
}

function summarizeTool(args: Record<string, unknown>): ToolResult {
  const target = args.target ?? args.input ?? args;
  return {
    status: "pass",
    value: {
      kind: "summary",
      text: summarizeValue(target),
      target
    },
    summary: "Summary created"
  };
}

function askTool(args: Record<string, unknown>): ToolResult {
  const options = Array.isArray(args.options) ? args.options : undefined;
  const answer = options?.[0] ?? "mock answer";

  return {
    status: "pass",
    value: {
      kind: "answer",
      question: args.question ?? args.input,
      answer
    },
    summary: "Mock answer selected"
  };
}

function exportTool(args: Record<string, unknown>): ToolResult {
  const format = String(args.format ?? "json");
  return {
    status: "pass",
    value: {
      kind: "artifact",
      format,
      uri: `mock://export/${format}`,
      target: args.target ?? args.input ?? args
    },
    summary: `Artifact exported as ${format}`
  };
}

function runTool(args: Record<string, unknown>): ToolResult {
  return {
    status: "pass",
    value: {
      kind: "command_result",
      command: args.command ?? args.input,
      target: args.target,
      exitCode: 0,
      stdout: "Mock RUN did not execute a real shell command."
    },
    summary: "Mock command completed"
  };
}

function readTool(args: Record<string, unknown>, ctx: { readFile(path: string): unknown }): ToolResult {
  const path = String(args.path ?? args.input ?? "");
  const stored = ctx.readFile(path);
  const value =
    stored ??
    (path === "app"
      ? {
          kind: "file_bundle",
          path,
          files: [{ path: "app/index.ts", content: "export const broken = true;\n" }],
          issues: ["failing_tests"],
          patches: 0
        }
      : { kind: "file", path, content: "" });

  return {
    status: "pass",
    value,
    summary: `Read ${path || "mock path"}`
  };
}

function writeTool(args: Record<string, unknown>, ctx: { writeFile(path: string, content: unknown): void }): ToolResult {
  const path = String(args.path ?? args.input ?? "");
  const content = args.content ?? "";
  ctx.writeFile(path, content);

  return {
    status: "pass",
    value: {
      kind: "write_result",
      path,
      content,
      written: true
    },
    summary: `Wrote ${path || "mock path"}`
  };
}

function extractIssues(value: unknown): string[] {
  if (value !== null && typeof value === "object" && Array.isArray((value as { issues?: unknown }).issues)) {
    return [...((value as { issues: string[] }).issues ?? [])];
  }

  return [];
}

function patchValue(target: unknown, patch: Record<string, unknown>): unknown {
  if (target !== null && typeof target === "object" && !Array.isArray(target)) {
    const current = target as Record<string, unknown>;
    return {
      ...current,
      ...patch,
      patches: typeof current.patches === "number" ? current.patches + 1 : 1
    };
  }

  return {
    kind: "patched_value",
    target,
    ...patch,
    patches: 1
  };
}

function summarizeValue(value: unknown): string {
  if (value === null) {
    return "null";
  }

  if (typeof value !== "object") {
    return String(value);
  }

  if ("kind" in value && typeof (value as { kind?: unknown }).kind === "string") {
    return `${(value as { kind: string }).kind} object`;
  }

  return `object with ${Object.keys(value).length} keys`;
}
