from __future__ import annotations

import re
from typing import Any


SCHEMA_VERSION = "0.1.0"


def make_capsule_template(
    form: str,
    *,
    language: str = "en",
    part_of_speech: str = "unknown",
    source_id: str | None = None,
) -> dict[str, Any]:
    cleaned_form = form.strip()
    if not cleaned_form:
        raise ValueError("form must not be empty")

    normalized_form = cleaned_form.casefold()
    slug = slugify(normalized_form)
    provenance_id = source_id or f"manual-{language}-{slug}"

    return {
        "schema_version": SCHEMA_VERSION,
        "id": f"ei:{language}:{slug}",
        "capsule_type": "lexeme",
        "surface": {
            "form": cleaned_form,
            "normalized_form": normalized_form,
            "language": language,
            "script": "unknown",
            "part_of_speech": part_of_speech,
        },
        "morphology": {
            "summary": "Unknown morphology. Replace this with segmented morphemes and glosses.",
            "segments": [
                {
                    "text": cleaned_form,
                    "role": "unknown",
                    "source_language": "unknown",
                    "glosses": ["unknown"],
                    "certainty": "unknown",
                    "provenance_refs": [provenance_id],
                }
            ],
            "certainty": "unknown",
            "provenance_refs": [provenance_id],
        },
        "etymology": {
            "summary": "Unknown etymological lineage. Replace this with attested, reconstructed, or disputed source forms.",
            "lineage": [],
            "certainty": "unknown",
            "provenance_refs": [provenance_id],
        },
        "semantic_drift": {
            "summary": "Unknown semantic development. Replace this with historical sense changes where evidence is available.",
            "developments": [],
        },
        "present_usage": {
            "summary": "Current usage not yet analyzed.",
            "senses": [
                {
                    "id": f"{slug}.sense.unknown",
                    "definition": "Current sense to be supplied.",
                    "register": "unknown",
                    "domains": ["unknown"],
                    "connotations": ["unknown"],
                    "synonyms": ["unknown"],
                    "examples": [],
                    "certainty": "unknown",
                    "provenance_refs": [provenance_id],
                }
            ],
        },
        "cultural_frame": {
            "summary": "Cultural and discourse frames not yet analyzed.",
            "frames": [],
        },
        "pragmatics": {
            "summary": "Pragmatic stance not yet analyzed.",
            "stances": [
                {
                    "label": "unknown",
                    "valence": "context_dependent",
                    "description": "Determine whether usage is praising, critical, neutral, ironic, branding-oriented, or otherwise stance-marked.",
                    "cues": ["unknown"],
                    "certainty": "unknown",
                    "provenance_refs": [provenance_id],
                }
            ],
        },
        "expansion": {
            "paragraph": f"{cleaned_form} has not yet been expanded into an etymonoetic capsule. Fill each layer before treating this as semantic data.",
            "trace": [
                {
                    "layer": "uncertainty",
                    "contribution": "This starter capsule is a valid placeholder, not a completed lexical analysis.",
                    "provenance_refs": [provenance_id],
                }
            ],
        },
        "capsule_summary": f"Draft semantic capsule for {cleaned_form}; analysis pending.",
        "relations": [],
        "provenance": [
            {
                "id": provenance_id,
                "source_type": "manual",
                "citation": f"Manual starter capsule for {cleaned_form}.",
                "note": "Generated by the EI CLI. Replace placeholders and add cited sources before production use.",
            }
        ],
        "uncertainty": {
            "overall": "unknown",
            "unresolved_questions": [
                "Add cited sources for morphology and etymology.",
                "Separate historical semantic drift from current usage.",
                "Identify pragmatic stances and discourse cues.",
            ],
        },
    }


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.casefold()).strip("-")
    return slug or "unknown"
