use anyhow::{Result, bail};
use serde_json::{Value, json};

pub const SCHEMA_VERSION: &str = "0.1.0";

pub fn make_capsule_template(
    form: &str,
    language: &str,
    part_of_speech: &str,
    source_id: Option<&str>,
    provenance: Option<Value>,
) -> Result<Value> {
    let cleaned_form = form.trim();
    if cleaned_form.is_empty() {
        bail!("form must not be empty");
    }

    let normalized_form = cleaned_form.to_lowercase();
    let slug = slugify(&normalized_form);

    let (provenance_id, provenance_entry) = match provenance {
        Some(mut entry) => {
            let id = source_id
                .map(str::to_owned)
                .or_else(|| entry.get("id").and_then(Value::as_str).map(str::to_owned))
                .unwrap_or_else(|| format!("manual-{language}-{slug}"));
            entry["id"] = json!(id);
            (id, entry)
        }
        None => {
            let id = source_id
                .map(str::to_owned)
                .unwrap_or_else(|| format!("manual-{language}-{slug}"));
            let entry = json!({
                "id": id,
                "source_type": "manual",
                "citation": format!("Manual starter capsule for {cleaned_form}."),
                "note": "Generated by the EI CLI. Replace placeholders and add cited sources before production use."
            });
            (id, entry)
        }
    };

    Ok(json!({
        "schema_version": SCHEMA_VERSION,
        "id": format!("ei:{language}:{slug}"),
        "capsule_type": "lexeme",
        "surface": {
            "form": cleaned_form,
            "normalized_form": normalized_form,
            "language": language,
            "script": "unknown",
            "part_of_speech": part_of_speech
        },
        "morphology": {
            "summary": "Unknown morphology. Replace this with segmented morphemes and glosses.",
            "segments": [{
                "text": cleaned_form,
                "role": "unknown",
                "source_language": "unknown",
                "glosses": ["unknown"],
                "certainty": "unknown",
                "provenance_refs": [provenance_id]
            }],
            "certainty": "unknown",
            "provenance_refs": [provenance_id]
        },
        "etymology": {
            "summary": "Unknown etymological lineage. Replace this with attested, reconstructed, or disputed source forms.",
            "lineage": [],
            "certainty": "unknown",
            "provenance_refs": [provenance_id]
        },
        "semantic_drift": {
            "summary": "Unknown semantic development. Replace this with historical sense changes where evidence is available.",
            "developments": []
        },
        "present_usage": {
            "summary": "Current usage not yet analyzed.",
            "senses": [{
                "id": format!("{slug}.sense.unknown"),
                "definition": "Current sense to be supplied.",
                "register": "unknown",
                "domains": ["unknown"],
                "connotations": ["unknown"],
                "synonyms": ["unknown"],
                "examples": [],
                "certainty": "unknown",
                "provenance_refs": [provenance_id]
            }]
        },
        "cultural_frame": {
            "summary": "Cultural and discourse frames not yet analyzed.",
            "frames": []
        },
        "pragmatics": {
            "summary": "Pragmatic stance not yet analyzed.",
            "stances": [{
                "label": "unknown",
                "valence": "context_dependent",
                "description": "Determine whether usage is praising, critical, neutral, ironic, branding-oriented, or otherwise stance-marked.",
                "cues": ["unknown"],
                "certainty": "unknown",
                "provenance_refs": [provenance_id]
            }]
        },
        "expansion": {
            "paragraph": format!("{cleaned_form} has not yet been expanded into an etymonoetic capsule. Fill each layer before treating this as semantic data."),
            "trace": [{
                "layer": "uncertainty",
                "contribution": "This starter capsule is a valid placeholder, not a completed lexical analysis.",
                "provenance_refs": [provenance_id]
            }]
        },
        "capsule_summary": format!("Draft semantic capsule for {cleaned_form}; analysis pending."),
        "relations": [],
        "provenance": [provenance_entry],
        "uncertainty": {
            "overall": "unknown",
            "unresolved_questions": [
                "Add cited sources for morphology and etymology.",
                "Separate historical semantic drift from current usage.",
                "Identify pragmatic stances and discourse cues."
            ]
        }
    }))
}

pub fn slugify(value: &str) -> String {
    let mut slug = String::new();
    let mut last_was_dash = false;

    for ch in value.to_lowercase().chars() {
        if ch.is_ascii_alphanumeric() {
            slug.push(ch);
            last_was_dash = false;
        } else if !last_was_dash && !slug.is_empty() {
            slug.push('-');
            last_was_dash = true;
        }
    }

    while slug.ends_with('-') {
        slug.pop();
    }

    if slug.is_empty() {
        "unknown".to_owned()
    } else {
        slug
    }
}
